name = "Nexus Realms"
author = "Carlos"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa512602f9c16900941172b3d9a02829a99a07f68fdd8095f620a4dd2d93bcd3"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
