name = "Nexus Realms"
author = "Carlos"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf7cd955d61cd9807d761d253083a41ba6644f675d68f6e11e563fd7f2342fc2"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
