name = "Nexus Realms"
author = "Carlos"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5f1d987af325883a972e197eac8350e73e622c1aa4c88180d51641653520de1"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
