[gunfire_generation]
enable_generation = false

[generalsounds_generation]
enable_generation = false

[debugging]
debug = false

[weather]
thunder_range_multiplier = 0.8

[tacz_gun_modifiers]
modifiers = ["pistol=1.0,3.8", "sniper=1.0,8.0", "rifle=1.0,6.5", "shotgun=1.0,4.8", "smg=1.0,3.0", "rpg=1.0,10.0", "mg=1.0,4.0"]

[tacz_silenced_guns]
ids = ["daffas_arsenal:hk45_sup", "daffas_arsenal:apacoba9_sup"]

[tacz_silencer_modifiers]
enabled = false
modifiers = ["pistol=1.0,0.4", "sniper=1.0,0.35", "rifle=1.0,0.4", "shotgun=1.0,0.45", "smg=1.0,0.4", "rpg=1.0,0.5", "mg=1.0,0.45"]
