[debugging]
debug = false

[entity_voice_generation]
enable_generation = false

[whisper_configs]
whisper_range_multiplier = 0.5
whisper_speed_multiplier = 0.8

[mob_speed_boost]
mob_speed_boost_enabled = false

[misc_config]
thunder_range_multiplier = 0.5
sneaking_range_multiplier = 0.5

[sculk_sensor_config]
sculk_sensor_enabled = false
sculk_sensor_threshold = -45.0
sculk_sensor_range = 16
sculk_sensor_frequency = 8

[armor_effects]
effects = ["minecraft:diamond_helmet=1.0,0.5", "minecraft:diamond_chestplate=1.0,0.7"]

[death_angels_config]
death_angels_threshold = -30.0

[quiet_place_overman_config]
quiet_place_overman_threshold = -30.0
