# Applied by Default Options only once, on a fresh instance.
defaultDifficulty = "NORMAL"
defaultResourcePacks = [
    "xali's Enhanced Vanilla -1.11.2b-rev.54d51d4.zip",
    "Stay_True_1.20.zip",
    "true_nitwit_texture.zip",
    "Vulmoons calaclysm remake_0.5.zip",
    "【Released】BDHill Reforge the Sword Edge-2.0_1.20.1.zip",
    "trident trail.zip",
    "DMC5 yamato for Nightfall v1.2.zip",
    "EclecticTrove-1.20.1-1.3.0.zip",
    "Mandalas GUI - Dark Mode KOTS Compat 2.8.zip",
    "OurStory FTB Theme - 2.0 - 1.20.1.zip"
]
lockDifficulty = false
