[starry_trail]
intensity = 0.0
starScale = 1.2
opacity = 0.0
layers = 1
texture = "fancy_trail:textures/effect/star.png"

[chromatic_aberration]
chromaticEffect = 0.0

[additional_particles]
speed = 0.0
particleType = "minecraft:end_rod"

[flowing_effect]
intensity = 0.0
speed = 0.0

[common_air_trail]
isOpenAir = false
