[SomniumBar]
	PositionX = 0.0
	PositionY = -11.0

[DimensionSettings]
	Difficulty = 3.0
	GuideBook = true
	PotatoParticles = false
	PotatoShaders = true
	OreRarity = 10.0
	StructureGen = 15.0